name: Update

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  inject:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update files
        run: |
          # Replace old URL
          find . -type f \
            ! -path "./.git/*" \
            ! -path "./.github/workflows/*" \
            -exec sed -i \
              's@https://ruvs.in/melamrahul.github.io@https://rahul.serv00.net/melamrahul.github.io@g' {} +

          # Remove unwanted YouTube AI icon
          find . -type f \
            ! -path "./.git/*" \
            ! -path "./.github/workflows/*" \
            -exec sed -i \
              's@<img src="https://melamrahul.github.io/yt-ai/yt-ai-icon.png" />@@g' {} +

          # Replace converter iframe
          find . -type f \
            ! -path "./.git/*" \
            ! -path "./.github/workflows/*" \
            -exec sed -i \
              's@<iframe id="converterFrame" src="https://rahul.serv00.net/melamrahul.github.io" scrolling="no"></iframe>@<iframe id="converterFrame" src="https://mr.ruvs.in" scrolling="no" loading="eager"></iframe>@g' {} +

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add .

          if git diff --cached --quiet; then
            echo "No changes."
          else
            git commit -m "Update"
            git push
          fi
