name: update

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: update
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: update
        shell: bash
        run: |
          set -euxo pipefail

          find . -type f -name "*.html" -print0 | while IFS= read -r -d '' file; do
            echo "Processing: $file"

            perl -0pi -e '
              s/\?v=1\.0\b/?v={{ site.github.build_revision }}/g;
            ' "$file"
          done

      - name: update
        shell: bash
        run: |
          set -euxo pipefail

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add .

          if git diff --cached --quiet; then
            echo "No changes"
            exit 0
          fi

          git commit -m "update"
          git push
